code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension azemoh.one-monokai
code --install-extension ckolkman.vscode-postgres
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.next-js
code --install-extension frinkr.pdf
code --install-extension JakeBecker.elixir-ls
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension Perkovec.emoji
code --install-extension PKief.material-icon-theme
code --install-extension pmneo.tsimporter
code --install-extension PulkitGangwar.nextjs-snippets
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension teabyii.ayu
code --install-extension usernamehw.errorlens
code --install-extension wholroyd.HCL
code --install-extension yzane.markdown-pdf